apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: keycloak
        image: "{{ .Values.image }}"
        env:
          - name: KEYCLOAK_FRONTEND_URL
            value: https://keycloak.local/admin/master
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
          - name: DB_VENDOR
            value: postgres
          - name: DB_ADDR
            value: {{ .Values.postgresqlHost | quote }}
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: database
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}
                key: password
        ports:
          - name: http
            containerPort: 8080
        livenessProbe:
          httpGet:
            path: /realms/master
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /realms/master
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
