image: "bitnami/keycloak:latest"
secretName: "keycloak-secret"
replicaCount: 1
ingress:
  enabled: true
  hostname: "keycloak.local"
auth:
  adminUser: "admin"
  adminPassword: "adminpassword"
postgresqlHost: "postgres.local"
