apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: postgresql
        image: "{{ .Values.image }}"
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}-db-secret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}-db-secret
                key: password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: {{ .Values.secretName }}-db-secret
                key: database
        ports:
          - name: postgres
            containerPort: 5432
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
          {{- if .Values.persistence.enabled }}
          - name: data
            mountPath: /bitnami/postgresql
          {{- end }}
