apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.secretName }}
  labels:
    chart: {{ .Chart.Name }}
type: Opaque
data:
  username: {{ .Values.globalDatabase.username | b64enc }}
  password: {{ .Values.globalDatabase.password | b64enc }}
  database: {{ .Values.globalDatabase.database | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pgadmin.secretName }}
  labels:
    chart: {{ .Chart.Name }}
type: Opaque
data:
  username: {{ .Values.pgadmin.admin.email | b64enc }}
  password: {{ .Values.pgadmin.admin.password | b64enc }}
