apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.secretName }}-db-secret
  labels:
    chart: {{ .Values.postgresql.secretName }}
type: Opaque
data:
  username: {{ .Values.globalDatabase.username | b64enc }}
  password: {{ .Values.globalDatabase.password | b64enc }}
  database: {{ .Values.globalDatabase.database | b64enc }}
