apiVersion: v1
kind: Pod
metadata:
  name:  "{{ .Chart.Name }}-test-connection"
  labels:
    chart: "{{ .Chart.Name }}"
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  containers:
  - name: test-container
    image: curlimages/curl:latest
    command:
      - "sh"
      - "-c"
      - >
        set -e;
        echo "Testing Keycloak...";
        curl -kL --fail --max-time 5 http://keycloak.default.svc.cluster.local/ > /dev/null ;
        echo "Keycloak OK";

        echo "Testing Website...";
        curl -kL --fail --max-time 5 https://website.default.svc.cluster.local/ > /dev/null ;
        echo "Website OK";

        echo "All tests passed!";
  restartPolicy: Never
